-- Bronze Layer Tables
CREATE TABLE IF NOT EXISTS RAW_DATASET_1 (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST INT,
    CITY_DISTRICT_ID INT,
    RPTG_AMT FLOAT,
    CURRENCY_CD VARCHAR,
    ORDER_QTY INT
);

CREATE TABLE IF NOT EXISTS RAW_DATASET_2 (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST BIGINT,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR,
    RPTG_AMT FLOAT,
    CURRENCY_CD VARCHAR,
    ORDER_QTY INT
);

CREATE TABLE IF NOT EXISTS RAW_MAPPING (
    CITY_DISTRICT_ID INT PRIMARY KEY,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR
);

-- Silver Layer Tables
CREATE TABLE IF NOT EXISTS PROCESSED_DATASET (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST BIGINT,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR,
    RPTG_AMT FLOAT,
    CURRENCY_CD VARCHAR,
    ORDER_QTY INT
);

CREATE TABLE IF NOT EXISTS EXCEPTIONS_DATASET (
    ORDER_ID VARCHAR PRIMARY KEY,
    VALIDATION_ERR VARCHAR
);

CREATE TABLE IF NOT EXISTS TRANSLATIONS_CITY_MAPPING (
    SHIP_TO_CITY_CD VARCHAR PRIMARY KEY,
    SHIP_TO_CITY_CD_ENG VARCHAR
);

CREATE TABLE IF NOT EXISTS TRANSLATIONS_DISTRICT_MAPPING (
    SHIP_TO_DISTRICT_NAME VARCHAR PRIMARY KEY,
    SHIP_TO_DISTRICT_NAME_ENG VARCHAR
);

CREATE TABLE IF NOT EXISTS CURRENCY_CODE_MAPPING (
    CURRENCY_CD VARCHAR PRIMARY KEY,
    MULTIPLIER FLOAT,
    DATE_RECORDED DATE
);

-- Gold Layer Table
CREATE TABLE IF NOT EXISTS CURATED_DATASET (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST BIGINT,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR,
    SHIP_TO_DISTRICT_NAME_ENG VARCHAR,
    SHIP_TO_CITY_ENG VARCHAR,
    RMB_DOLLARS FLOAT,
    ORDER_QTY INT
);

-- Creating Proper Indexes on PK Columns
-- Bronze Layer Indexes
CREATE INDEX idx_raw_dataset_1_city_district_id ON RAW_DATASET_1 (CITY_DISTRICT_ID);
CREATE INDEX idx_raw_dataset_2_ship_to_city_cd ON RAW_DATASET_2 (SHIP_TO_CITY_CD);
CREATE INDEX idx_raw_dataset_2_ship_to_district_name ON RAW_DATASET_2 (SHIP_TO_DISTRICT_NAME);
CREATE INDEX idx_raw_mapping_ship_to_city_cd ON RAW_MAPPING (SHIP_TO_CITY_CD);
CREATE INDEX idx_raw_mapping_ship_to_district_name ON RAW_MAPPING (SHIP_TO_DISTRICT_NAME);

-- Silver Layer Indexes
CREATE INDEX idx_processed_dataset_ship_to_city_cd ON PROCESSED_DATASET (SHIP_TO_CITY_CD);
CREATE INDEX idx_processed_dataset_ship_to_district_name ON PROCESSED_DATASET (SHIP_TO_DISTRICT_NAME);
CREATE INDEX idx_exceptions_dataset_order_id ON EXCEPTIONS_DATASET (ORDER_ID);
CREATE INDEX idx_currency_code_mapping_currency_cd ON CURRENCY_CODE_MAPPING (CURRENCY_CD);

-- Gold Layer Indexes
CREATE INDEX idx_curated_dataset_ship_to_city_cd ON CURATED_DATASET (SHIP_TO_CITY_CD);
CREATE INDEX idx_curated_dataset_ship_to_district_name ON CURATED_DATASET (SHIP_TO_DISTRICT_NAME);
CREATE INDEX idx_curated_dataset_ship_to_district_name_eng ON CURATED_DATASET (SHIP_TO_DISTRICT_NAME_ENG);
CREATE INDEX idx_curated_dataset_ship_to_city_eng ON CURATED_DATASET (SHIP_TO_CITY_ENG);