import duckdb
from constants import DUCKDB_FILE_PATH

# Define the path to the DuckDB database file
duckdb_file_path = DUCKDB_FILE_PATH

# DDL statements
ddl_statements = """
-- Bronze Layer Tables
CREATE TABLE IF NOT EXISTS RAW_DATASET_1 (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST VARCHAR,
    CITY_DISTRICT_ID INT,
    RPTG_AMT DECIMAL(18,2),
    CURRENCY_CD VARCHAR,
    ORDER_QTY VARCHAR
);
CREATE TABLE IF NOT EXISTS RAW_MAPPING (
    CITY_DISTRICT_ID INT PRIMARY KEY,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR
);
CREATE TABLE IF NOT EXISTS RAW_DATASET_2 (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST BIGINT,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR,
    RPTG_AMT DECIMAL(18,2),
    CURRENCY_CD VARCHAR,
    ORDER_QTY INT
);

-- Silver Layer Tables
CREATE TABLE IF NOT EXISTS PROCESSED_DATASET (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST BIGINT,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR,
    RPTG_AMT DECIMAL(18,2),
    CURRENCY_CD VARCHAR,
    ORDER_QTY INT
);

CREATE TABLE IF NOT EXISTS EXCEPTIONS_DATASET (
    ORDER_ID VARCHAR PRIMARY KEY,
    VALIDATION_ERR VARCHAR
);

CREATE TABLE IF NOT EXISTS TRANSLATIONS_CITY_MAPPING (
    SHIP_TO_CITY_CD VARCHAR PRIMARY KEY,
    SHIP_TO_CITY_CD_ENG VARCHAR,
    METADATA JSON,
    PROVINCE VARCHAR,
    PER_CAPITA_USD VARCHAR,
    TOTAL_GDP_USD VARCHAR
);

CREATE TABLE IF NOT EXISTS TRANSLATIONS_DISTRICT_MAPPING (
    SHIP_TO_DISTRICT_NAME VARCHAR PRIMARY KEY,
    SHIP_TO_DISTRICT_NAME_ENG VARCHAR,
    METADATA JSON
);

CREATE TABLE IF NOT EXISTS CURRENCY_CODE_MAPPING (
    CURRENCY_CD VARCHAR PRIMARY KEY,
    MULTIPLIER FLOAT,
    DATE_RECORDED DATE
);

-- Gold Layer Table
CREATE TABLE IF NOT EXISTS CURATED_DATASET (
    ORDER_ID VARCHAR PRIMARY KEY,
    ORDER_TIME_PST BIGINT,
    SHIP_TO_CITY_CD VARCHAR,
    SHIP_TO_DISTRICT_NAME VARCHAR,
    SHIP_TO_DISTRICT_NAME_ENG VARCHAR,
    SHIP_TO_CITY_CD_ENG VARCHAR,
    RMB_DOLLARS DECIMAL(18,2),
    ORDER_QTY INT
);

-- Creating Proper Indexes on PK Columns
"""

# Create a DuckDB connection to a persistent database file
con = duckdb.connect(database=duckdb_file_path, read_only=False)

# Execute the DDL statements
con.execute(ddl_statements)

# Verify by listing all tables
tables = con.execute("SHOW TABLES").fetchall()
print("Tables in the database:", tables)

# Close the DuckDB connection
con.close()
